#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

require 'json'

plan = {
  redundant: false,
  horizontal: false,
  user: 'nanobox',
  users: [{
    username: 'nanobox',
    meta: {}
  }],
  ips: [:default],
  port: 7419,
  behaviors: [:migratable]
}

puts JSON.pretty_generate(plan)
